apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: queue-master
spec:
  serviceAccountName: queue-master-docker-hub
  taskRef:
    name: queue-master
  params:
  - name: IMAGE
    value: "rayanah/queue-master"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: level-3-project
