apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment 
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: rayanah/payment
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 0
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: payment
