apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: catalogue-pr
spec:
  pipelineRef:
    name: catalogue-p 
  serviceAccountName: sock-shop-sa
  resources:
    - name: level-3-project
      resourceRef:
        name: sock-catalogue
