apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: load-test
spec:
  serviceAccountName: load-test-docker-hub
  taskRef:
    name: load-test
  params:
  - name: IMAGE
    value: "rayanah/load-test"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: load-test
