apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipping-run
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: shipping-deploy-kubectl
  resources:
    inputs:
    - name: user-db-pr
      resourceRef:
        name: user-db-pr
