apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: shipping-run
spec:
  serviceAccountName: sock-shop
  pipelineRef:
    name: shipping-pipeline
  resources:
    - name: final
      resourceRef:
        name: shipping-pr
