apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shipping-pipeline
spec:
  resources:
    - name: shipping-pr
      type: git
  tasks:
    - name: build
      taskRef:
        name: shipping
      resources:
        inputs: 
        - name: shipping-pr
          resource: shipping-pr
    - name: shipping-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: shipping-deploy-kubectl
      resources:
        inputs:
        - name: shipping-pr
          resource: shipping-pr
    - name: shipping-e2e-test
      runAfter: ["shipping-deploy-kubectl"]
      taskRef:
        name: shipping-e2e-test
      resources:
        inputs:
        - name: shipping-pr
          resource: shipping-pr
    - name: shipping-deploy-to-prod
      runAfter: ["shipping-e2e-test"]
      taskRef:
        name: shipping-deploy-to-prod
      resources:
        inputs:
        - name: shipping-pr
          resource: shipping-pr
