apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: catalogue-db-deploy-kubectl
  serviceAccountName: catalogue-db-deploy
spec:
  params:
    - name: pathToYamlFile
      type: string
      description: The path to the yaml file to deploy within the git source
      default: $(resources.inputs.catalogue-db-pr.path)/catalogue/cataloguedb-dep-ser.yaml
    - name: namespace
      default: test
  resources:
    inputs:
      - name: catalogue-db-pr
        type: git
  steps:
   - name: run-kubectl
     image: lachlanevenson/k8s-kubectl
     command: ["kubectl"]
     args:
       - "apply"
       - "-f"
       - "$(params.pathToYamlFile)"
       - "-n"
       - "$(params.namespace)"

