apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-db-run
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: catalogue-db-deploy-kubectl
  resources:
    inputs:
    - name: catalogue-db-pr
      resourceRef:
        name: catalogue-db-pr
