apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catalogue-db-pipeline
spec:
  resources:
    - name: final
      type: git
  tasks:
    - name: build
      taskRef:
        name: catalogue-db
      resources:
        inputs: 
        - name: catalogue-db-pr
          resource: final
    - name: catalogue-deploy-db-kubectl
      runAfter: ["build"]
      taskRef:
        name: catalogue-deploy-db-kubectl
      resources:
        inputs:
        - name: catalogue-db-pr
          resource: final
