apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: queue-run
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: queue-deploy-kubectl
  resources:
    inputs:
    - name: queue-pr
      resourceRef:
        name: queue-pr
