apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipping-run-images
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: shipping
  resources:
    inputs:
    - name: shipping-pr
      resourceRef:
        name: shipping-pr
  params:
    - name: IMAGE
      value: "rayanah/shipping"
