apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: orders-run
spec:
  serviceAccountName: sock-shop
  pipelineRef:
    name: orders-pipeline
  resources:
    - name:  orders-pr
      resourceRef:
        name: orders-pr
