--- 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cart-db
  labels:
    app: cart-db
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: cart-db
  template:
    metadata:
      labels:
        app: cart-db
    spec:
      containers:
      - name: carts-db
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: cart-db
  labels:
    app: cart-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: cart-db
---
