apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: orders-pipeline
spec:
  resources:
    - name: orders-pr
      type: git
  tasks:
    - name: build
      taskRef:
        name: orders
      resources:
        inputs: 
        - name: orders-pr
          resource: orders-pr
    - name: orders-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: orders-deploy-kubectl
      resources:
        inputs:
        - name: orders-pr
          resource: orders-pr
