apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: queue-run
spec:
  serviceAccountName: sock-shop
  pipelineRef:
    name: queue-pipeline
  resources:
    - name: final
      resourceRef:
        name: queue-pr
