apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: queue-run-images
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: queue
  resources:
    inputs:
    - name: queue-pr
      resourceRef:
        name: queue-pr
  params:
    - name: IMAGE
      value: "rayanah/queue-master"
