apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-db-run
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: user-db-deploy-kubectl
    resources:
    inputs:
    - name: user-db-pr
      resourceRef:
        name: user-db-pr
