apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: carts-pipeline
spec:
  resources:
    - name: carts-pr
      type: git
  tasks:
    - name: build
      taskRef:
        name: carts
      resources:
        inputs: 
        - name: carts-pr
          resource: carts-pr
    - name: carts-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: carts-deploy-kubectl
      resources:
        inputs:
        - name: carts-pr
          resource: carts-pr
    - name: cart-e2e-test
      runAfter: ["carts-deploy-kubectl"]
      taskRef:
        name: cart-e2e-test
      resources:
        inputs:
        - name: carts-pr
          resource: carts-pr
    - name: cart-deploy-to-prod
      runAfter: ["cart-e2e-test"]
      taskRef:
        name: cart-deploy-to-prod
      resources:
        inputs:
        - name: carts-pr
          resource: carts-pr
