apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: carts-run-images
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: carts
  resources:
    inputs:
    - name: carts-pr
      resourceRef:
        name: carts-pr
  params:
    - name: IMAGE
      value: "rayanah/carts"
