--- 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    name: elasticsearch
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch
        ports:
         - name: elasticsearch
           containerPort: 9200
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
  namespace: logging
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    name: elasticsearch
