apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-db
spec:
  serviceAccountName: user-db-docker-hub
  taskRef:
    name: user-db
  params:
  - name: IMAGE
    value: "rayanah/user-db"
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: user-db
