apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: catalogue-run
spec:
  serviceAccountName: sock-shop
  pipelineRef:
    name: catalogue-pipeline
  resources:
    - name: final
      resourceRef:
        name: catalogue-pr
