apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-run-images
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: catalogue
  resources:
    inputs:
    - name: catalogue-pr
      resourceRef:
        name: catalogue-pr
  params:
    - name: IMAGE
      value: "rayanah/catalogue"
