apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: dockr-runner
spec:
  serviceAccountName: rayanah-docker-hub
  taskRef:
    name: dockr
  params:
  - name: IMAGE
    value: "rayanah/e2e-tests"
  resources:
    inputs:
    - name: sock-shop
      resourceRef:
        name: sock-shop
