apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: e2e-run
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: e2e-deploy-kubectl
  resources:
    inputs:
    - name: e2e-pr
      resourceRef:
        name: e2e-pr
