apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: e2e-pr
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/rayanah/level-3-project.git
