apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
spec:
  resources:
    inputs:
    - name: e2e-pr
      type: git
  params:
  - name: IMAGE
    description: Name (reference) of the image to build.
    default: "rayanah/e2e-tests"
  steps:
  - name: run-test
    image: rayanah/e2e-tests
    script: |
      #!/bin/sh
       pwd
       ls e2e-pr
       rm -rf node_modules package-lock.json
       npm init -y
       npm install --save chrome-remote-interface chrome-launcher mocha express request body-parser sinon chai chai-http http
       source  e2e-pr/e2e-js-test/runner.sh
