apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: e2e-test
spec:
  resources:
    inputs:
    - name: e2e-pr
      type: git
  params:
  - name: IMAGE
    description: Name (reference) of the image to build.
    default: "rayanah/e2e-tests"
  - name: IMAGE_TAG
    default: "latest"
  - name: CONTEXT
    description: The build context used by Kaniko.
    default: $(resources.inputs.e2e-pr.path)/e2e-js-test
  - name: pathToYamlFile
    type: string
    description: The path to the yaml file to deploy within the git source
    default: $(resources.inputs.e2e-pr.path)/e2e-js-test/e2e-dep.yaml
  - name: namespace
    default: test
  steps:
  - name: run-test
    image: "$(params.IMAGE):$(params.IMAGE_TAG)"
    command: ["/bin/sh"]
    args:
      - "-c"
      - "make itest"
    securityContext:
     runAsUser: 0
  - name: run-kubectl
    image: lachlanevenson/k8s-kubectl
    command: ["kubectl"]
    args:
      - "apply"
      - "-f"
      - "$(params.pathToYamlFile)"
      - "-n"
      - "$(params.namespace)"
