apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: payment-pipeline
spec:
  resources:
    - name: final
      type: git
  tasks:
    - name: build
      taskRef:
        name: payment
      resources:
        inputs: 
        - name: payment-pr
          resource: final
    - name: payment-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: payment-deploy-kubectl
      resources:
        inputs:
        - name: payment-pr
          resource: final
