apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: payment-run
spec:
  serviceAccountName: sock-shop
  pipelineRef:
    name: payment-pipeline
  resources:
    - name: payment-pr
      resourceRef:
        name: payment-pr
