apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: user-db-run-images
spec:
  serviceAccountName: sock-shop
  taskRef:
    name: user-db
  resources:
    inputs:
    - name: user-db-pr
      resourceRef:
        name: user-db-pr
  params:
    - name: IMAGE
      value: "rayanah/user-db"
