apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: front-end-pipeline
spec:
  resources:
    - name: final
      type: git
  tasks:
    - name: build
      taskRef:
        name: front-end
      resources:
        inputs: 
        - name: front-end-pr
          resource: final
    - name: front-end-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: front-end-deploy-kubectl
      resources:
        inputs:
        - name: front-end-pr
          resource: final
