apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: front-end-pipeline
spec:
  resources:
    - name: front-end-pr
      type: git
  tasks:
    - name: build
      taskRef:
        name: front-end
      resources:
        inputs: 
        - name: front-end-pr
          resource: front-end-pr
    - name: front-end-deploy-kubectl
      runAfter: ["build"]
      taskRef:
        name: front-end-deploy-kubectl
      resources:
        inputs:
        - name: front-end-pr
          resource: front-end-pr
    - name: front-end-e2e-test
      runAfter: ["front-end-deploy-kubectl"]
      taskRef:
        name: front-end-e2e-test
      resources:
        inputs:
        - name: front-end-pr
          resource: front-end-pr
    - name: front-end-deploy-to-prod
      runAfter: ["front-end-e2e-test"]
      taskRef:
        name: front-end-deploy-to-prod
      resources:
        inputs:
        - name: front-end-pr
          resource: front-end-pr
