kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: front-end-role
rules:
- apiGroups: ["serving.knative.dev", "apps", "", "extensions"]
  resources: ["services", "deployments", "deployments.apps", "replicasets", "pods"]
  verbs: ["get", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: front-end-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: front-end-role
subjects:
- kind: ServiceAccount
  name: front-end-deploy
