apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: front-end-run
spec:
  serviceAccountName: front-end-deploy
  taskRef:
    name: front-end
  resources:
    inputs:
    - name: level-3-project
      resourceRef:
        name: front-end-pr
  params:
    - name: IMAGE
      value: "rayanah/front-end"
