apiVersion:  tekton.dev/v1beta1
kind: Task
metadata:
  name: front-end-run
spec:
  inputs:
    resources:
      - name: level-3-project
        type: git
    params:
      - name: pathToContext
        description: The path to the build context, used by Kaniko - within the workspace
        default: level-3-project/front-end/
      - name: pathToYamlFile
        description: The path to the yaml file to deploy within the git source
        default: front-end-dep.yaml
      - name: imageUrl
        description: Url of image repository
        default: rayanah/front-end
      - name: imageTag
        description: Tag of the images to be used.
        default: "latest"
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
        - "-i"
        - "-e"
        - "s;IMAGE;$(inputs.params.imageUrl):$(inputs.params.imageTag);g"
        - "$(inputs.resources.git-source.path)/$(inputs.params.pathToContext)/$(inputs.params.pathToYamlFile)"
    - name: deploy-app
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
        - "apply"
        - "-f"
        - "$(inputs.resources.git-source.path)/$(inputs.params.pathToContext)/$(inputs.params.pathToYamlFile)"
