--- 
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: rayanah/user
        env:
         - name: mongo
           value: user-db:27017
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 0
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app: cart
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cart
---
